### ISSUE TITLE
It doesn’t seem to work on 14.2 taurine

### ISSUE THREAD

**Issue by p0liak** [YuzuZensai/iOS-DiscordPresence#1]
Hi, I’ve tested it with youtube, iSTB, Soundclound and some more apps from the store and I had no rich presence (checked with both my iphone and another device). Like said in the title, I’m on 14.2 taurine, does it matter or is it related to an update from discord ?

**Comment by YuzuZensai** [comment]
Sadly, the API at discord only support "games" that exists (Same package name) in the Google Play Store.

This is not really a rich presence but more like playing *game* status.
The API is originally designed for Samsung Game Launcher, this tweak just reimplement the game detection function from the Samsung Game Launcher. The presence is handled at server side by discord.
